### ISSUE TITLE
Publish results of the analysis

### ISSUE THREAD

**Issue by fschwebel** [philipperemy/tensorflow-1.4-billion-password-analysis#4]
The code is interesting but just a mean. Did you achieve the objective mentioned? Did you publish some results?

**Comment by philipperemy** [comment]
@fschwebel still working on it!

**Comment by philipperemy** [comment]
Just for info, I'll push soon the first model.

You can see the progress here: https://github.com/philipperemy/tensorflow-1.4-billion-password-analysis/tree/model

**Comment by denemmy** [comment]
Can you share your trained model, please?

**Comment by zixia** [comment]
Hello @philipperemy , did you get any updates for the results after working for this?

**Comment by clintonm9** [comment]
@philipperemy very cool project! Is this something you are still working on or have you moved to something else?

**Comment by philipperemy** [comment]
@clintonm9 its still in my list and I would love to continue working on it but at the moment Im busy with other projects..

**Comment by agtejeo** [comment]
Dear friend, I tried to run this project... and I get some errors (running not in virtual env); these are:

./process_and_train.sh .
Remove --max_num_files to process the entire dataset (few hours of processing in total).
Traceback (most recent call last):
  File "run_data_processing.py", line 101, in <module>
    run()
  File "run_data_processing.py", line 97, in run
    on_file_read_call_back_class=ReducePasswordsOnSimilarEmailsCallback)
  File "/home/agtejeo/Documentos/br/tensor/utils.py", line 38, in process
    all_filenames = glob(breach_compilation_folder + '/**/*', recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'
Traceback (most recent call last):
  File "run_encoding.py", line 6, in <module>
    from data_gen import LazyDataLoader, build_vocabulary, get_chars_and_ctable
  File "/home/agtejeo/Documentos/br/tensor/data_gen.py", line 53
SyntaxError: Non-ASCII character '\xef' in file /home/agtejeo/Documentos/br/tensor/data_gen.py on line 53, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
  File "train_model.py", line 218
    print('guess  :', guess, end=' ')
                                ^
SyntaxError: invalid syntax

any suggestion?

**Comment by clintonm9** [comment]
@agtejeo I don't think `recursive=True` was added to glob until version 3.5 of Python. What version of Python are you running?

**Comment by agtejeo** [comment]
python --version
Python 2.7.15rc1

**Comment by clintonm9** [comment]
Please use python3
